services:
  db:
    image: postgres:17-alpine
    container_name: cc_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: cc_adminer
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db_data:
